FROM debian:bullseye-slim

LABEL "name"="oci-ansible" "version"="v6"

RUN mkdir /ansible \
    && mkdir -p /root/.ssh \
    && chmod 755 /root/.ssh \
    && sed -i -e's/ main/ main contrib non-free/g' /etc/apt/sources.list \
    && apt-get clean \
    && apt-get -y update \
    && apt-get -y install --no-install-recommends apt-utils dpkg-dev \
    && apt-get -y install --no-install-recommends \
	libncurses6 libncursesw6 ncurses-bin ncurses-term \
	ca-certificates \
        locales \
        iproute2 \
        net-tools \
	tcpdump \
	tcptrace \
	nmap \
	netcat \
	procps \
	htop \
        lsof \
	coreutils \
	bsdutils \
	debianutils \
	dnsutils \
	diffutils \
	findutils \
	gnupg-utils \
	ng-utils \
	renameutils \
	sharutils \
	zutils \
	zip \
	unzip \
	lz4 \
	zstd \
	lzop \
        gzip \
        p7zip-full \
        p7zip-rar \
	pigz \
        pixz \
        plzip \
        xz-utils \
        lrzip \
        zpaq \
	python3-pip \
	python3-dev \
	git \
	openssl \
	openssh-client \
	sshpass \
	curl \
	wget \
	jq \
	vim \
	mc \
        ranger \
    && sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN pip3 install --upgrade pip cffi \
	&& pip3 install \
         ansible==5.6.0 \
         ansible-compat==2.0.2 \
         ansible-core==2.12.4 \
         ansible-lint==6.0.2 \
         ansible-modules-hashivault==4.6.8 \
         attrs==21.4.0 \
         bcrypt==3.2.0 \
         bracex==2.2.1 \
         certifi==2021.10.8 \
         charset-normalizer==2.0.12 \
         commonmark==0.9.1 \
         cryptography==36.0.2 \
         distro==1.7.0 \
         docker==5.0.3 \
         docker-compose==1.29.2 \
         dockerpty==0.4.1 \
         docopt==0.6.2 \
         enrich==1.2.7 \
         hvac==0.11.2 \
         idna==3.3 \
         Jinja2==3.1.1 \
         jmespath==1.0.0 \
         jsonschema==3.2.0 \
         MarkupSafe==2.1.1 \
         mitogen==0.3.2 \
         ntlm-auth==1.5.0 \
         openstacksdk==1.1.0 \
         packaging==21.3 \
         paramiko==2.10.3 \
         pathspec==0.9.0 \
         proxmoxer==2.0.1 \
         psycopg2-binary==2.9.3 \
         pycparser==2.21 \
         pyzabbix==1.2.1 \
         Pygments==2.11.2 \
         PyNaCl==1.5.0 \
         pyparsing==3.0.8 \
         pyrsistent==0.18.1 \
         python-dotenv==0.20.0 \
         pywinrm==0.4.3 \
         PyYAML==5.4.1 \
         requests==2.27.1 \
         requests-ntlm==1.1.0 \
         resolvelib==0.5.4 \
         rich==12.2.0 \
         ruamel.yaml==0.17.21 \
         ruamel.yaml.clib==0.2.6 \
         six==1.16.0 \
         subprocess-tee==0.3.5 \
         texttable==1.6.4 \
         urllib3==1.26.9 \
         wcmatch==8.3 \
         websocket-client==0.59.0 \
         xmltodict==0.12.0 \
         yamllint==1.26.3 \
         zabbix-api==0.5.4 \
	 python-openstackclient \
	 python-cinderclient \
	 python-glanceclient \
	 python-neutronclient \
	 python-novaclient \
	 python-swiftclient \
    && rm -rf /root/.cache/pip

ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]

STOPSIGNAL SIGINT

CMD [ "ansible-playbook" ]

WORKDIR /ansible


